### ISSUE TITLE
`window` variable is not set to the same device as `img1`

### ISSUE THREAD

**Issue by gregjohnso** [Po-Hsun-Su/pytorch-ssim#4]
`*** RuntimeError: tensors are on different GPUs` error when input cuda input is not on gpu 0

**Comment by Po-Hsun-Su** [comment]
Hi Greg,
I have merged your commit  881d21 to address this issue. 
Thank you for letting me know the issue.

**Comment by gregjohnso** [comment]
Great! I made a 3D version too, if you want it :)

**Comment by DaniMlk** [comment]
Hi everybody 
I recently saw your perfect code wrote SSIM loss for grayscale Image. Is there any version of it that can use for the RGB version of an image?
@gregjohnso @Po-Hsun-Su

**Comment by Po-Hsun-Su** [comment]
Issue resolved by https://github.com/Po-Hsun-Su/pytorch-ssim/commit/881d210fba3fc9af9d67787db11ae29b8f118268
