### ISSUE TITLE
Is there a particular reason that the constant doesn't multiple L?

### ISSUE THREAD

**Issue by teracamo** [Po-Hsun-Su/pytorch-ssim#7]
Most implementation such as this http://www.cns.nyu.edu/~lcv/ssim/ssim_index.m also have L, but I understand L scales with bit sizes so that probably won't do much difference for float images?

**Comment by Po-Hsun-Su** [comment]
I assume that the dynamic range of input image is 0~1. So there is no L in my implementation.

**Comment by teracamo** [comment]
「Po-Hsun Su <notifications@github.com>」在 2017年11月19日 週日，05:39 寫道：

**Comment by teracamo** [comment]
I see

**Comment by Ikhwansong** [comment]
I think this question makes me improve the understanding in depth.
